# Generated by Django 5.0.2 on 2024-03-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_ticket_solution_ticket_status_ticket_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solution',
            field=models.TextField(default='', max_length=255),
        ),
    ]
