# Generated by Django 5.0.2 on 2024-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0006_alter_ticket_technician_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='document_upload',
            field=models.FileField(blank=True, default='', upload_to='complaint'),
        ),
    ]
