# Generated by Django 5.0.2 on 2024-03-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0007_ticket_document_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[(3, 'HIGH'), (2, 'MEDIUM'), (1, 'LOW')], default=1, max_length=255),
        ),
    ]
