# Generated by Django 3.2 on 2024-04-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0010_ticket_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.CharField(choices=[('poor', 'poor'), ('average', 'average'), ('good', 'good'), ('excellent', 'excellent')], default='poor', max_length=255),
        ),
    ]
